### ISSUE TITLE
Coulomb * Volt = Joule

### ISSUE THREAD

**Issue by pedroilidio** [gjvnq/LabIFSC#14]
Aparentemente não é reconhecida a relação CV=J:

```
>>> E = Medida((3,1), 'C V')
>>> E.converta('J')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/LabIFSC/medida.py", line 114, in converta
    self.checa_dim(m)
  File "/usr/lib/python3.7/site-packages/LabIFSC/medida.py", line 94, in checa_dim
    raise ValueError("dimensões físicas incompatíveis: {} vs {} ({} vs. {})".format(dimensao_em_texto(self.dimensao), dimensao_em_texto(outro.dimensao), self, outro))
ValueError: dimensões físicas incompatíveis: L2A-1M1T-2I1 vs L2M1T-2 (3±1 C V vs. 1.0±0 J)
```

**Comment by gjvnq** [comment]
Resolvido na versão v0.1.10
