### ISSUE TITLE
Problema na exponenciação de valores negativos

### ISSUE THREAD

**Issue by pedroilidio** [gjvnq/LabIFSC#16]
Acontece o seguinte problema ao exponenciar uma Medida negativa:

```
>>> y = Medida(-5)
>>> y**2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/LabIFSC/medida.py", line 189, in __pow__
    return self.__pow__(Medida(outro))
  File "/usr/lib/python3.7/site-packages/LabIFSC/medida.py", line 212, in __pow__
    sf += (math.log(A)*sB)**2
ValueError: math domain error
```

**Comment by gjvnq** [comment]
Corrigido na versão v0.1.12
